apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deployment
spec:
  selector:
    matchLabels:
      app: rest
  replicas: 2
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: rest
        image: novrian/k8s-rest:1.0.1
        ports:
        - containerPort: 8080
